server:
  address: 0.0.0.0
  port: 7080

management:
  endpoints:
    web:
      exposure:
        include: prometheus,temporalworkerinfo
spring:
  application:
    name: priority-service
  web:
    cors:
      allowed-origins:
        - https://localhost:4000
      allowed-methods:
        - GET
        - POST
      allowed-headers: "*"
      allowed-credentials: true

  temporal:
    namespace: ${TEMPORAL_NAMESPACE:default}
    workersAutoDiscovery:
      packages:
        - com.demo.priority
    connection:
      target: ${TEMPORAL_ADDRESS:127.0.0.1:7233}

    workers:
      - name: PriorityWorkflow
        task-queue: PriorityWorkflowTQ
        workflow-classes:
          - com.demo.priority.service.workflows.PriorityWorkflowImpl
        capacity:
          max-concurrent-workflow-task-pollers: 10
      - name: PriorityActivity
        task-queue: PriorityActivityTQ
        activity-beans:
          - priorityActivityImpl
        capacity:
          # Limiting activity progression to max of 5 so we have queues.
          max-concurrent-activity-executors: 5
      - name: Fairness
        task-queue: fairness-queue
        workflow-classes:
          - com.demo.priority.service.workflows.FairnessWorkflowImpl
        activity-beans:
          - fairnessActivityImpl
        capacity:
          # Configure both workflow pollers and activity executors for a single worker on fairness-queue.
          max-concurrent-workflow-task-pollers: 10
          max-concurrent-activity-executors: 5
